/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  kubernetes: [
    {
      type: 'autogenerated',
      dirName: 'kubernetes',
    }
  ],
  linux: [
    {
      type: 'autogenerated',
      dirName: 'linux',
    },
  ],
  'dev&ops': [
    {
      type: 'autogenerated',
      dirName: 'dev&ops',
    },
  ],
  others: [
    {
      type: 'autogenerated',
      dirName: 'others',
    },
  ],  
};

module.exports = sidebars;
